services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: poll_app
      POSTGRES_PASSWORD: poll_app
      POSTGRES_DB: poll_app
    ports: ["5432:5432"]
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-node-1:
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: ["7001:6379", "17001:16379"]
    volumes:
      - ./scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-node-1-data:/data
  redis-node-2:
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: ["7002:6379", "17002:16379"]
    volumes:
      - ./scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-node-2-data:/data
  redis-node-3:
    image: redis:7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: ["7003:6379", "17003:16379"]
    volumes:
      - ./scripts/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-node-3-data:/data
  redis-cluster-init:
    image: redis:7-alpine
    depends_on: [redis-node-1, redis-node-2, redis-node-3]
    command: >
      redis-cli --cluster create
      redis-node-1:6379 redis-node-2:6379 redis-node-3:6379
      --cluster-replicas 0 --cluster-yes

volumes:
  postgres-data:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
